// ===========================================================
// RTL generated by ActiveCore framework
// Date: 2021-12-29 18:15:48
// Copyright Alexander Antonov <antonov.alex.alex@gmail.com>
// ===========================================================

`ifndef __coproc_if_h_
`define __coproc_if_h_

`ifndef __genstructdel_resp_struct_
`define __genstructdel_resp_struct_
typedef struct packed {
	logic unsigned [31:0] rd0_wdata;
} resp_struct;
`endif // __genstructdel_resp_struct_

`ifndef __genstructdel_req_struct_
`define __genstructdel_req_struct_
typedef struct packed {
	logic unsigned [31:0] instr_code;
	logic unsigned [31:0] src0_data;
	logic unsigned [31:0] src1_data;
} req_struct;
`endif // __genstructdel_req_struct_

`endif // __coproc_if_h_
